version: '3'
services:
  #서비스 1 - react
  client:
    container_name: client
    # 도커 빌드 : dockerfile를 가진 경로
    build: 
      context: ./project_bmw_front
    volumes:
      - ./project_bmw_front:/app
      # (필수) 컨테이너에서 모듈과 빌드된 파일을 사용할 수 있도록 알려야함.
      - /app/node_modules
      - /app/build
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080
      # 리엑트 HMR(Hot Module Reload)을 위해 필요한 설정 + nginx 설정파일에서 소켓 설정 해야한다.
      - CHOKIDAR_USEPOLLING=true
    # react-script 3.4.1 부터 필요
    stdin_open: true             
    tty: true

  # 서비스 2 - nginx
  web:
    container_name: web
    build: 
      # client와 같은 이미지 사용
      context: ./project_bmw_front
    restart: always
    # 종속성 : client가 먼저 빌드되고 nginx가 빌드되도록 설정
    depends_on:
      - client
    ports:
      - '80:80'
    volumes:
      # (필수) 로컬 설정파일 => nginx 설정파일에 마운트
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/

# volumes:
#   test_volume:

# networks: 
#   backend:
#     driver: bridge
