version: '3'
services:
  # 서비스 1 - nginx + react
  web-client:
    container_name: web_client
    build: 
      # client와 같은 이미지 사용
      context: ./project_bmw_front
    restart: always
    # 종속성 : client가 먼저 빌드되고 nginx가 빌드되도록 설정
    # depends_on:
      # - client
    ports:
      - '80:80'
    volumes:
      # (필수) 로컬 설정파일 => nginx 설정파일에 마운트
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    stdin_open: true # docker run -i
    tty: true        # docker run -t

# volumes:
#   test_volume:

# networks: 
#   backend:
#     driver: bridge
